### PR TITLE
global cleanup `EOL` [ `\s+$` => `null` ]

### PR DESCRIPTION
**Pull request by xerc**
this should make other contributions a bit more easy to patch/merge

fyi/ did not touch `LICENSE.INCONSOLATA` cause it is `CRLF` formated

### CODE REVIEW

**Comment by xerc** [comment]
btw/ there is also a lot of mix'ed `\t` | `\s{2}`

**Comment by metafloor** [comment]
I just released version 4.3 and created a bunch of conflicts with your changes.  The reason is that development actually occurs under the develop branch and not on master.  The release script then syncs the two.  So ... I retab'd the files in your list (we switched our coding standard from tabs to spaces a few years back - so my vim settings starting mixing and matching).  And fixed up the svg tags and wrong comment.  The eol extra spaces are probably not going to get fixed - I don't see that as a big issue.

But I do appreciate you going over files.  I am typically the only one who ever looks at them! ;-)  If I missed any changes, please let me know.  Thanks again.

**Comment by xerc** [comment]
make sense to use `develop` ; i was just confused with this bunch of different changes (looked "old)

**Comment by xerc** [comment]
@metafloor its not a big effort to cleanup the EOL/EOF and TABs ; are you interested ?

**Comment by metafloor** [comment]
@xerc, sure.  If possible, please push the PR to the develop branch.  If it's on the master branch, I just need to copy some files around.

**Pull request closed without merging**
