### PR TITLE
[node] allow barcodes of different colors

### PR DESCRIPTION
**Pull request by terrancesnyder**
Allow rendering of barcodes of different colors, useful for branding barcodes (qrcodes, etc) with barcode color options. The missing piece here is also being able to change the color of the fonts rendered with the barcode, could not find an easy solution here but it would be great to allow changing the font color rendered.

### CODE REVIEW

**Comment by terrancesnyder** [comment]
If at all possible would love guidance on where to look for font color changes.

**Comment by metafloor** [comment]
Are these options what you are looking for?

https://github.com/bwipp/postscriptbarcode/wiki/Symbol-Colors

BWIPP uses the full rrggbb format for colors so I would prefer to stay with that.

**Comment by terryburton** [comment]
@metafloor:

CMYK is supported too and I should probably add support for HSB as this the third native to PS color space. Not sure whether frontends that have their own renderer will make use of this.

Also the options reference is a bit of an incomplete mess. Sorry, I'll work on this soon.

I've recently converted the examples in the symbologies and options reference sections over to using discrete Data/Options/Encoder fields rather than the PS syntax. Hopefully that makes referring directly to the BWIPP documentation less difficult to swallow.

**Comment by terrancesnyder** [comment]
@metafloor shows what I know.... i should of read that, but for whatever reason I could not find it at all - maybe examples on the home page with colors?

**Comment by metafloor** [comment]
I am not sure what you are trying to achieve here.  There are already `barcolor` and `textcolor` options.  And with this latest release, 2D symbols can now have text.

Can you please describe in better detail what is lacking in the current functionality.

**Comment by terryburton** [comment]
> And with this latest release, 2D symbols can now have text.

Indeed, I plan to go back through the 2D formats and add text where appropriate. https://github.com/bwipp/postscriptbarcode/issues/83

**Comment by metafloor** [comment]
Closing this in prep for the 2.0 release which (finally!) fixes this bug.

**Pull request closed without merging**
