### PR TITLE
Hide console logs by default

### PR DESCRIPTION
**Pull request by wmcmurray**
Firstly, thanks for this repo !!

I hided the console logs behind a variable set to `false` by default because I just used this module in a production project and I can't have so much logs generated on the production server.

I haven't done an interface to change the config from outside the module, but you could do it later if you want.

Oh and please `npm publish` if you accept this pull request ! :)

### CODE REVIEW

**Comment by hstonge** [comment]
+1

**Comment by metafloor** [comment]
The console logs have been removed in 0.14.2.  They should never have been there in the first place....

**Comment by hstonge** [comment]
Thanks a lot for the quick update !

**Comment by wmcmurray** [comment]
Perfect, thanks !

**Pull request closed without merging**
