### PR TITLE
Added a C40 encoder

### PR DESCRIPTION
**Pull request by BiosencyAdmin**
This encoder is based on the mailmark encoder and allows to encode a given number of characters in C40 without other constraints.

In our case, we need this encoder to follow some requirements of the french government regarding the data digitization of the french health system. (probably the same problematic as asked by @Epono in #245)
References for the curious : 
- [The whole project](https://industriels.esante.gouv.fr/en)
- [The requirements that brought me here (in french)](https://industriels.esante.gouv.fr/sites/default/files/media/document/ANS_Datamatrix_INS_v2.2.pdf)

Since I'm not familiar with postscript, there may be some mistakes, but the generated datamatrix works on my side.

I also modified the mailmark encoder  to use a `c40headerdatamatrix` variable instead of `mailmark`, for factorization's sake (behavior will be the same, with the new `c40headerlength` having a default value of 45)

### CODE REVIEW

**Comment by terryburton** [comment]
@metafloor I'll pick this up in BWIPP here: https://github.com/bwipp/postscriptbarcode/issues/216

**Comment by terryburton** [comment]
@BiosencyAdmin BWIPP is the PostScript library that BWIP-JS transliterates.

**Comment by terryburton** [comment]
From BWIPP release 2013-02-16 you can now do:

```
encoder: datamatrix
data: IS010000000000000000000000S1110086322083060S21.2.250.1.213.1.4.8^029S3MICHELINE JEANNE DENISE^029S4MICHU^029S5FS611/05/1945S706220
options: c40headerlength=26
```

**Comment by metafloor** [comment]
I will roll the new BWIPP release into bwip-js later today (late evening Colorado time).

**Comment by metafloor** [comment]
Using @terryburton's example data and options, release v3.3.0 is generating the following:

image

@BiosencyAdmin : Can you verify the format of the scanned barcode is correct for your needs?

**Comment by BiosencyAdmin** [comment]
Hi ! Thank you both for your quick reply and your time !





> Using @terryburton's example data and options, release v3.3.0 is generating the following:
> 
> image
> 
> @BiosencyAdmin : Can you verify the format of the scanned barcode is correct for your needs?

Tested : it works properly :)

**Comment by metafloor** [comment]
Good to hear.  I am going to close this out since the change was successfully incorporated upstream.

**Pull request closed without merging**
